apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app.default.tap.20231214170204.0.0+build.e7979dc
spec:
  refName: tanzu-java-web-app.default.tap
  version: 20231214170204.0.0+build.e7979dc
  releaseNotes: |
    Release v20231214170204.0.0+build.e7979dc of package tanzu-java-web-app.default.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.ryanbaker.io/tap-apps/workloads/tanzu-java-web-app-default-bundle@sha256:60075f9a620254bb75e143eaeefd4c87a6b293734f074b23e230c11211f9efd6
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

