apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app.default.tap.20231214042905.0.0+build.14d8043
spec:
  refName: tanzu-java-web-app.default.tap
  version: 20231214042905.0.0+build.14d8043
  releaseNotes: |
    Release v20231214042905.0.0+build.14d8043 of package tanzu-java-web-app.default.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.ryanbaker.io/tap-apps/workloads/tanzu-java-web-app-default-bundle@sha256:8dfb04ff3251de07de376111c6b38607a442c2dae80dafbdd6f67d417ed34c57
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

