---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: tanzu-java-web-app
spec:
 serviceAccountName: server-workload-installer  
 packageRef:
   refName: tanzu-java-web-app.dev-ns.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: tanzu-java-web-app-package-values # Secret created in previous step
---
apiVersion: v1
kind: Secret
metadata:
 name: tanzu-java-web-app-package-values
stringData:
 values.yaml: |
   ---
   replicas: 1
   hostname: ""
   workload_name: tanzu-java-web-app